### ISSUE TITLE
E2E : Movie form test fails with uncaught exception

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3842]
Getting an internal error during tests.

```
The following error originated from your application code, not from Cypress.

  > INTERNAL

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event.

```

Stack Trace:

```
    at new HttpsErrorImpl (http://localhost:4200/firebase-functions.js:78:25)
    at _errorForResponse (http://localhost:4200/firebase-functions.js:199:11)
    at Service.<anonymous> (http://localhost:4200/firebase-functions.js:737:22)
    at step (http://localhost:4200/vendor.js:132682:24)
    at Object.next (http://localhost:4200/vendor.js:132663:54)
    at fulfilled (http://localhost:4200/vendor.js:132653:59)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:683:161)
    at Zone.run (http://localhost:4200/polyfills.js:409:38)
    at <unknown> (http://localhost:4200/polyfills.js:1334:29)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:716:174)
From previous event:
    at run (http://localhost:4200/__cypress/runner/cypress_runner.js:169779:20)
    at $Cy.cy.<computed> [as clearCookies] (http://localhost:4200/__cypress/runner/cypress_runner.js:170232:12)
    at Context.runnable.fn (http://localhost:4200/__cypress/runner/cypress_runner.js:170458:22)
    at callFn (http://localhost:4200/__cypress/runner/cypress_runner.js:104227:22)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:4200/__cypress/runner/cypress_runner.js:104214:8)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:176303:29)
From previous event:
    at Object.onRunnableRun (http://localhost:4200/__cypress/runner/cypress_runner.js:176291:21)
    at $Cypress.action (http://localhost:4200/__cypress/runner/cypress_runner.js:166430:62)
    at Test.Runnable.run (http://localhost:4200/__cypress/runner/cypress_runner.js:174622:14)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:4200/__cypress/runner/cypress_runner.js:104886:11)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:105012:13)
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:104795:15)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:104805:8)
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:104707:15)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:104773:6)
    at timeslice (http://localhost:4200/__cypress/runner/cypress_runner.js:98699:28)

```

This is blocking the movie form test as it prevents Cypress from executing the test.

**Comment by xmano** [comment]
PR #3862 fixed this by accepting cookies in Landing Page.
