### ISSUE TITLE
Add gsutils command on dockerFile used by CI

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3851]
to prevent : 
```
{ Error: Command failed: gsutil -m rm -r "gs://blockframes-staging.appspot.com/*"
/bin/sh: 1: gsutil: not found
```

**Comment by phpgeekfr** [comment]
```
CommandException: 1 files/objects could not be removed.
{ Error: Command failed: gsutil -m rm -r "gs://blockframes-staging.appspot.com/*"
CommandException: 1 files/objects could not be removed.
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at /home/circleci/repo/dist/apps/backend-ops/main.js:11410:195
    at catchErrors (/home/circleci/repo/dist/apps/backend-ops/main.js:11580:16)
    at /home/circleci/repo/dist/apps/backend-ops/main.js:11410:90
    at step (/home/circleci/repo/dist/apps/backend-ops/main.js:11364:23)
    at Object.next (/home/circleci/repo/dist/apps/backend-ops/main.js:11345:53)
    at fulfilled (/home/circleci/repo/dist/apps/backend-ops/main.js:11336:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  status: 1,
  signal: null,
  output:
   [ null,
     <Buffer >,
     <Buffer 43 6f 6d 6d 61 6e 64 45 78 63 65 70 74 69 6f 6e 3a 20 31 20 66 69 6c 65 73 2f 6f 62 6a 65 63 74 73 20 63 6f 75 6c 64 20 6e 6f 74 20 62 65 20 72 65 6d ... > ],
  pid: 930,
  stdout: <Buffer >,
  stderr:
   <Buffer 43 6f 6d 6d 61 6e 64 45 78 63 65 70 74 69 6f 6e 3a 20 31 20 66 69 6c 65 73 2f 6f 62 6a 65 63 74 73 20 63 6f 75 6c 64 20 6e 6f 74 20 62 65 20 72 65 6d ... > }
Copying storage bucket from blockframe-ci to your local project's storage bucket...
Running command: gsutil -m cp -r gs://blockframes-ci-storage-backup/storage-backup-04-10-2020/* gs://blockframes-staging.appspot.com
ServiceException: 401 Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket.
CommandException: 1 file/object could not be transferred.
{ Error: Command failed: gsutil -m cp -r gs://blockframes-ci-storage-backup/storage-backup-04-10-2020/* gs://blockframes-staging.appspot.com
ServiceException: 401 Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket.
CommandException: 1 file/object could not be transferred.
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at /home/circleci/repo/dist/apps/backend-ops/main.js:11414:195
    at catchErrors (/home/circleci/repo/dist/apps/backend-ops/main.js:11580:16)
    at /home/circleci/repo/dist/apps/backend-ops/main.js:11414:90
    at step (/home/circleci/repo/dist/apps/backend-ops/main.js:11364:23)
    at Object.next (/home/circleci/repo/dist/apps/backend-ops/main.js:11345:53)
    at fulfilled (/home/circleci/repo/dist/apps/backend-ops/main.js:11336:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  status: 1,
  signal: null,
  output:
   [ null,
     <Buffer >,
     <Buffer 53 65 72 76 69 63 65 45 78 63 65 70 74 69 6f 6e 3a 20 34 30 31 20 41 6e 6f 6e 79 6d 6f 75 73 20 63 61 6c 6c 65 72 20 64 6f 65 73 20 6e 6f 74 20 68 61 ... > ],
  pid: 2424,
  stdout: <Buffer >,
  stderr:
   <Buffer 53 65 72 76 69 63 65 45 78 63 65 70 74 69 6f 6e 3a 20 34 30 31 20 41 6e 6f 6e 79 6d 6f 75 73 20 63 61 6c 6c 65 72 20 64 6f 65 73 20 6e 6f 74 20 68 61 ... > }
Storage synced!
Preparing database & storage by running migrations...
start the migration process...
```
