### ISSUE TITLE
Jest config issues.

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4696]
With latest Nx 11 finding issue with running jest unit-tests

```
$ npx jest twilio.spec.ts
 FAIL  apps/backend-functions/src/twilio.spec.ts
  ● Test suite failed to run

    apps/backend-functions/src/twilio.spec.ts:58:17 - error TS2339: Property 'toMatchObject' does not exist on type 'Assertion'.

    58       expect(e).toMatchObject(new Error(`No 'eventId' params, this parameter is mandatory !`));
                       ~~~~~~~~~~~~~
    apps/backend-functions/src/twilio.spec.ts:75:26 - error TS2551: Property 'toMatch' does not exist on type 'Assertion'. Did you mean 'match'?

    75     expect(output.error).toMatch('UNKNOWN_EVENT');
                                ~~~~~~~
      node_modules/cypress/types/chai/index.d.ts:217:9
        217         match: Match;
                    ~~~~~
        'match' is declared here.
```

There is conflict with cypress types.

There are 2 issues - one is workspace related and other individual jest config related.

This issue tracks the problem with jest config. Workspace issue will be addressed by a different PR.

##  Requirements of tool setup

[ ] Able to run unit-test from CLI (Local & CI)
[ ] Able to run individual specs eg media.service.spec.ts
[ ] Should be able to test any type of app  (angular, backend, w/o firestore emulator)

### Notes:

1. Due to changes in new workspace, some of the tests need to be modified (NO_ENT err for files)

1.

**Comment by xmano** [comment]
Trying with latest jest. However get the issues:

```
$ npm i -D jest ts-jest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: blockframes@0.0.2
npm ERR! Found: @angular/common@11.0.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"11.0.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=6.0.0 <11" from akita-ng-fire@4.1.1
npm ERR! node_modules/akita-ng-fire
npm ERR!   akita-ng-fire@"^4.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See E:\Node\.npm\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\Node\.npm\_logs\2021-01-08T14_46_03_871Z-debug.log

```

**Comment by xmano** [comment]
New config with Nx 11 is different. After applying new config find 2 issues:

```
$ npx jest media.service.spec.ts
 FAIL  libs/media/src/lib/+state/media.service.spec.ts
  ● Test suite failed to run

    SyntaxError: D:\C8\blockframes-dev\libs\media\src\lib\+state\media.service.spec.ts: Unexpected token, expected ";" (13:13)

      11 |
      12 | describe('Media Service Test Suite', () => {
    > 13 |   let service: MediaService;
         |              ^
      14 |   let db: AngularFirestore;
      15 |   let storage: AngularFireStorage;
      16 |   const TESTDATA: UploadData = {

      at Parser._raise (node_modules/@babel/parser/src/parser/error.js:60:45)
      at Parser.raiseWithData (node_modules/@babel/parser/src/parser/error.js:55:17)
      at Parser.raise (node_modules/@babel/parser/src/parser/error.js:39:17)
```

This issue is fixed by running jest using nx command  like this:

```
> nx run backend-functions:test --t=twilio

```

However this causes a problem while running individual spec files 

```
$ npx jest -t=media.service.spec.ts
Error: Can't find a root directory while resolving a config file path.
Provided path to resolve: D:\C8\blockframes-dev\apps\libs
cwd: D:\C8\blockframes-dev
    at _default (D:\C8\blockframes-dev\node_modules\jest-config\build\resolveConfigPath.js:106:11)
    at readConfig (D:\C8\blockframes-dev\node_modules\jest-config\build\index.js:213:49)
    at D:\C8\blockframes-dev\node_modules\jest-config\build\index.js:447:18
    at Array.map (<anonymous>)
    at readConfigs (D:\C8\blockframes-dev\node_modules\jest-config\build\index.js:441:10)
    at async runCLI (D:\C8\blockframes-dev\node_modules\@jest\core\build\cli\index.js:230:59)
    at async Object.run (D:\C8\blockframes-dev\node_modules\jest\node_modules\jest-cli\build\cli\index.js:163:37)

```

**Comment by xmano** [comment]
Able to run the tests

![image](https://user-images.githubusercontent.com/8731418/104480133-3ed84080-55ea-11eb-8b32-66ea22f39c5b.png)

Problem was with preset:
\libs\user\jest.config.js

```
module.exports = {
  name: 'user',
  preset: '../../jest.preset.js',
  :
};
```

preset should point to correct jest.preset.js in the root.
