### ISSUE TITLE
backend-ops unit tests are failing

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4741]
Due to change over to new jest configs there might be some refactor / fixing of unit-tests needed:

![image](https://user-images.githubusercontent.com/8731418/104592396-29b7ec00-5694-11eb-8392-87ce55fbfda1.png)

**Comment by xmano** [comment]
Issue with DB Cleaning:

  ● DB cleaning script › should remove incorrect attributes from users

    expect(received).toEqual(expected) // deep equality

    Expected: 1
    Received: 0

      63 |     // Check if data have been correctly added
      64 |     expect(usersBefore.docs.length).toEqual(2);
    > 65 |     expect(organizations.docs.length).toEqual(1);
         |                                       ^
      66 |
      67 |     const organizationIds = organizations.docs.map(ref => ref.id);
      68 |

      at src/db-cleaning.spec.ts:65:39
      at step (src/db-cleaning.spec.ts:33:23)
      at Object.next (src/db-cleaning.spec.ts:14:53)
      at fulfilled (src/db-cleaning.spec.ts:5:58)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:143:47)
      at ../../node_modules/zone.js/dist/zone.js:891:38
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:421:35)

  ● DB cleaning script › should remove unexpected users from auth

    expect(received).toEqual(expected) // deep equality

    Expected: 3
    Received: 0

      87 |     // Check if data have been correctly added
      88 |     const usersBefore = await getCollectionRef('users');
    > 89 |     expect(usersBefore.docs.length).toEqual(3);
         |                                     ^
      90 |
      91 |     // See auth users
      92 |     adminAuth.users = [

      at src/db-cleaning.spec.ts:89:37
      at step (src/db-cleaning.spec.ts:33:23)
      at Object.next (src/db-cleaning.spec.ts:14:53)
      at fulfilled (src/db-cleaning.spec.ts:5:58)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:143:47)
      at ../../node_modules/zone.js/dist/zone.js:891:38
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:421:35)

Test Suites: 2 failed, 1 passed, 3 total
Tests:       4 failed, 18 passed, 22 total
Snapshots:   0 total
Time:        39.871 s
Ran all test suites.

**Comment by xmano** [comment]
Issue with storage cleaning


 FAIL  apps/backend-ops/src/storage-cleaning.spec.ts (36.862 s)
  ● Console

    console.warn
      {"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}

      at write (../../node_modules/firebase-functions/lib/logger.js:12:78)
      at Object.warn (../../node_modules/firebase-functions/lib/logger.js:63:5)
      at Object.setup (../../node_modules/firebase-functions/lib/setup.js:56:22)
      at Object.<anonymous> (../../node_modules/firebase-functions/lib/index.js:69:9)

    console.warn
      Please ensure the following variable is set in .env : IMGIX_TOKEN

      50 | export function warnMissingVars(): void | never {
      51 |   const warn = (key: string, msg: string) => {
    > 52 |     console.warn(`Please ensure the following variable is set in .env : ${key}`);
         |             ^
      53 |     console.warn(`More info: ${msg}\n`);
      54 |   };
      55 |   // Use '||' instead of '??' to detect empty string

      at warn (../../libs/firebase-utils/src/lib/util.ts:52:13)
      at ../../libs/firebase-utils/src/lib/util.ts:57:75
          at Array.map (<anonymous>)
      at warnMissingVars (../../libs/firebase-utils/src/lib/util.ts:56:46)
      at Object.loadAdminServices (../../libs/firebase-utils/src/lib/util.ts:87:3)
      at src/storage-cleaning.spec.ts:13:27
      at step (src/storage-cleaning.spec.ts:33:23)
      at Object.next (src/storage-cleaning.spec.ts:14:53)

    console.warn
      More info: API key for imgIx CDN is missing. Please see: https://www.notion.so/cascade8/Setup-ImgIx-c73142c04f8349b4a6e17e74a9f2209a


      51 |   const warn = (key: string, msg: string) => {
      52 |     console.warn(`Please ensure the following variable is set in .env : ${key}`);
    > 53 |     console.warn(`More info: ${msg}\n`);
         |             ^
      54 |   };
      55 |   // Use '||' instead of '??' to detect empty string
      56 |   if (!missingVarsMessageShown) requiredVars.map(

      at warn (../../libs/firebase-utils/src/lib/util.ts:53:13)
      at ../../libs/firebase-utils/src/lib/util.ts:57:75
          at Array.map (<anonymous>)
      at warnMissingVars (../../libs/firebase-utils/src/lib/util.ts:56:46)
      at Object.loadAdminServices (../../libs/firebase-utils/src/lib/util.ts:87:3)
      at src/storage-cleaning.spec.ts:13:27
      at step (src/storage-cleaning.spec.ts:33:23)
      at Object.next (src/storage-cleaning.spec.ts:14:53)

    console.warn
      Please ensure the following variable is set in .env : PROJECT_ID

      50 | export function warnMissingVars(): void | never {
      51 |   const warn = (key: string, msg: string) => {
    > 52 |     console.warn(`Please ensure the following variable is set in .env : ${key}`);
         |             ^
      53 |     console.warn(`More info: ${msg}\n`);
      54 |   };
      55 |   // Use '||' instead of '??' to detect empty string

      at warn (../../libs/firebase-utils/src/lib/util.ts:52:13)
      at ../../libs/firebase-utils/src/lib/util.ts:57:75
          at Array.map (<anonymous>)
      at warnMissingVars (../../libs/firebase-utils/src/lib/util.ts:56:46)
      at Object.loadAdminServices (../../libs/firebase-utils/src/lib/util.ts:87:3)
      at src/storage-cleaning.spec.ts:13:27
      at step (src/storage-cleaning.spec.ts:33:23)
      at Object.next (src/storage-cleaning.spec.ts:14:53)

    console.warn
      More info: Please specify your Firebase projectId in your .env file. This is used when executing build and deploy commands, such as nx deploy or nx build


      51 |   const warn = (key: string, msg: string) => {
      52 |     console.warn(`Please ensure the following variable is set in .env : ${key}`);
    > 53 |     console.warn(`More info: ${msg}\n`);
         |             ^
      54 |   };
      55 |   // Use '||' instead of '??' to detect empty string
      56 |   if (!missingVarsMessageShown) requiredVars.map(

      at warn (../../libs/firebase-utils/src/lib/util.ts:53:13)
      at ../../libs/firebase-utils/src/lib/util.ts:57:75
          at Array.map (<anonymous>)
      at warnMissingVars (../../libs/firebase-utils/src/lib/util.ts:56:46)
      at Object.loadAdminServices (../../libs/firebase-utils/src/lib/util.ts:87:3)
      at src/storage-cleaning.spec.ts:13:27
      at step (src/storage-cleaning.spec.ts:33:23)
      at Object.next (src/storage-cleaning.spec.ts:14:53)

    console.log
      Cleaned 0/0 from "public/movie" directory.

      at Object.<anonymous> (src/storage-cleaning.ts:10:11)

    console.log
      Cleaned 0/0 from "public/movies" directory.

      at Object.<anonymous> (src/storage-cleaning.ts:12:11)

    console.log
      Cleaned 0/0 from "public/orgs" directory.

      at Object.<anonymous> (src/storage-cleaning.ts:14:11)

    console.log
      Cleaned 0/0 from "public/users" directory.

      at Object.<anonymous> (src/storage-cleaning.ts:16:11)

    console.log
      Cleaned 0/0 from "public/watermark" directory.

      at Object.<anonymous> (src/storage-cleaning.ts:18:11)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

  ● Storage cleaning script › should empty public/watermark directory if migration 29 went well

    expect(received).toEqual(expected) // deep equality

    Expected: 2
    Received: 3

      151 |     // Check if data have been correctly added
      152 |     const documents = await getCollectionRef('users');
    > 153 |     expect(documents.docs.length).toEqual(2);
          |                                   ^
      154 |
      155 |     const output = await cleanWatermarkDir(bucket);
      156 |     expect(output.total).toEqual(filesBefore.length);

      at src/storage-cleaning.spec.ts:153:35
      at step (src/storage-cleaning.spec.ts:33:23)
      at Object.next (src/storage-cleaning.spec.ts:14:53)
      at fulfilled (src/storage-cleaning.spec.ts:5:58)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:143:47)
      at ../../node_modules/zone.js/dist/zone.js:891:38
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:421:35)

  ● Storage cleaning script › should skip files while emptying public/watermark directory if migration 29 went badly

    expect(received).toEqual(expected) // deep equality

    Expected: 2
    Received: 0

      180 |     // Check if data have been correctly added
      181 |     const documents = await getCollectionRef('users');
    > 182 |     expect(documents.docs.length).toEqual(2);
          |                                   ^
      183 |
      184 |     const output = await cleanWatermarkDir(bucket);
      185 |     expect(output.total).toEqual(filesBefore.length);

      at src/storage-cleaning.spec.ts:182:35
      at step (src/storage-cleaning.spec.ts:33:23)
      at Object.next (src/storage-cleaning.spec.ts:14:53)
      at fulfilled (src/storage-cleaning.spec.ts:5:58)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:143:47)
      at ../../node_modules/zone.js/dist/zone.js:891:38
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:421:35)

 FAIL  apps/backend-ops/src/db-cleaning.spec.ts (38.037 s)
  ● Console

    console.warn
      {"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}

      at write (../../node_modules/firebase-functions/lib/logger.js:12:78)
      at Object.warn (../../node_modules/firebase-functions/lib/logger.js:63:5)
      at Object.setup (../../node_modules/firebase-functions/lib/setup.js:56:22)
      at Object.<anonymous> (../../node_modules/firebase-functions/lib/index.js:69:9)

    console.warn
      Please ensure the following variable is set in .env : IMGIX_TOKEN

      50 | export function warnMissingVars(): void | never {
      51 |   const warn = (key: string, msg: string) => {
    > 52 |     console.warn(`Please ensure the following variable is set in .env : ${key}`);
         |             ^
      53 |     console.warn(`More info: ${msg}\n`);
      54 |   };
      55 |   // Use '||' instead of '??' to detect empty string

      at warn (../../libs/firebase-utils/src/lib/util.ts:52:13)
      at ../../libs/firebase-utils/src/lib/util.ts:57:75
          at Array.map (<anonymous>)
      at warnMissingVars (../../libs/firebase-utils/src/lib/util.ts:56:46)
      at Object.loadAdminServices (../../libs/firebase-utils/src/lib/util.ts:87:3)
      at src/db-cleaning.spec.ts:28:27
      at step (src/db-cleaning.spec.ts:33:23)
      at Object.next (src/db-cleaning.spec.ts:14:53)

    console.warn
      More info: API key for imgIx CDN is missing. Please see: https://www.notion.so/cascade8/Setup-ImgIx-c73142c04f8349b4a6e17e74a9f2209a


      51 |   const warn = (key: string, msg: string) => {
      52 |     console.warn(`Please ensure the following variable is set in .env : ${key}`);
    > 53 |     console.warn(`More info: ${msg}\n`);
         |             ^
      54 |   };
      55 |   // Use '||' instead of '??' to detect empty string
      56 |   if (!missingVarsMessageShown) requiredVars.map(

      at warn (../../libs/firebase-utils/src/lib/util.ts:53:13)
      at ../../libs/firebase-utils/src/lib/util.ts:57:75
          at Array.map (<anonymous>)
      at warnMissingVars (../../libs/firebase-utils/src/lib/util.ts:56:46)
      at Object.loadAdminServices (../../libs/firebase-utils/src/lib/util.ts:87:3)
      at src/db-cleaning.spec.ts:28:27
      at step (src/db-cleaning.spec.ts:33:23)
      at Object.next (src/db-cleaning.spec.ts:14:53)

    console.warn
      Please ensure the following variable is set in .env : PROJECT_ID

      50 | export function warnMissingVars(): void | never {
      51 |   const warn = (key: string, msg: string) => {
    > 52 |     console.warn(`Please ensure the following variable is set in .env : ${key}`);
         |             ^
      53 |     console.warn(`More info: ${msg}\n`);
      54 |   };
      55 |   // Use '||' instead of '??' to detect empty string

      at warn (../../libs/firebase-utils/src/lib/util.ts:52:13)
      at ../../libs/firebase-utils/src/lib/util.ts:57:75
          at Array.map (<anonymous>)
      at warnMissingVars (../../libs/firebase-utils/src/lib/util.ts:56:46)
      at Object.loadAdminServices (../../libs/firebase-utils/src/lib/util.ts:87:3)
      at src/db-cleaning.spec.ts:28:27
      at step (src/db-cleaning.spec.ts:33:23)
      at Object.next (src/db-cleaning.spec.ts:14:53)

    console.warn
      More info: Please specify your Firebase projectId in your .env file. This is used when executing build and deploy commands, such as nx deploy or nx build


      51 |   const warn = (key: string, msg: string) => {
      52 |     console.warn(`Please ensure the following variable is set in .env : ${key}`);
    > 53 |     console.warn(`More info: ${msg}\n`);
         |             ^
      54 |   };
      55 |   // Use '||' instead of '??' to detect empty string
      56 |   if (!missingVarsMessageShown) requiredVars.map(

      at warn (../../libs/firebase-utils/src/lib/util.ts:53:13)
      at ../../libs/firebase-utils/src/lib/util.ts:57:75
          at Array.map (<anonymous>)
      at warnMissingVars (../../libs/firebase-utils/src/lib/util.ts:56:46)
      at Object.loadAdminServices (../../libs/firebase-utils/src/lib/util.ts:87:3)
      at src/db-cleaning.spec.ts:28:27
      at step (src/db-cleaning.spec.ts:33:23)
      at Object.next (src/db-cleaning.spec.ts:14:53)

    console.log
      Cleaned users

      at Object.<anonymous> (src/db-cleaning.ts:49:11)

    console.log
      Cleaned orgs

      at Object.<anonymous> (src/db-cleaning.ts:51:11)

    console.log
      Cleaned permissions

      at Object.<anonymous> (src/db-cleaning.ts:68:11)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Cleaned movies

      at Object.<anonymous> (src/db-cleaning.ts:70:11)

    console.log
      Cleaned docsIndex

      at Object.<anonymous> (src/db-cleaning.ts:72:11)

    console.log
      Cleaned notifications

      at Object.<anonymous> (src/db-cleaning.ts:74:11)

    console.log
      Cleaned invitations

      at Object.<anonymous> (src/db-cleaning.ts:76:11)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Deleted A.

      at Object.<anonymous> (src/db-cleaning.ts:198:17)

    console.log
      Deleted B.

      at Object.<anonymous> (src/db-cleaning.ts:198:17)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Deleted A and cleaned org and permissions orgA.

      at Object.<anonymous> (src/db-cleaning.ts:211:17)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

    console.log
      Processing chunk 1/1

      at Object.<anonymous> (../../libs/firebase-utils/src/lib/firebase-utils.ts:67:28)

**Comment by phpgeekfr** [comment]
to test but should be fixed by #4678

**Comment by xmano** [comment]
Tests are passing. Closing this issue.

![image](https://user-images.githubusercontent.com/8731418/105372285-7028c000-5c2b-11eb-9e23-3b70c98e1185.png)
