### ISSUE TITLE
Fix failing unit test in firebase-utils

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4838]
Got a failure while running unit-test on CI

```
  ● Test util.ts generator function getCollectionInBatches › should return batches of the correct size

    expect.assertions(3)

    Expected three assertions to be called but received zero assertion calls.

       7 |     const batchSize = 10
       8 |     let iterations = 3;
    >  9 |     expect.assertions(iterations);
         |            ^
      10 |     const docs = util.getCollectionInBatches(usersRef, 'uid', batchSize)
      11 |     for await (const chunk of docs) {
      12 |       expect(chunk.length).toBe(batchSize)

      at src/lib/util.spec.ts:9:12
      at step (src/lib/util.spec.ts:52:23)
      at Object.next (src/lib/util.spec.ts:33:53)
      at src/lib/util.spec.ts:27:71
      at Object.<anonymous>.__awaiter (src/lib/util.spec.ts:23:12)
      at Object.<anonymous> (src/lib/util.spec.ts:5:51)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.572 s
Ran all test suites.
```

**Comment by fritzschoff** [comment]
Hey @xmano I just run the test and it worked. Can you validate that on your side and if so, close the issue?

**Comment by xmano** [comment]
I think the tests are still skipped.. Will need to check on this.

**Comment by fritzschoff** [comment]
I removed the skip locally and run the test, it passed

**Comment by xmano** [comment]
Good catch we didn't try after Jest config changes. Will enable the test and close the issue. Thanks.

**Comment by xmano** [comment]
This test has been fixed via PR:
https://github.com/blockframes/blockframes/pull/5483
