### ISSUE TITLE
prepareForTestingBeta failed with PERMISSION_DENIED

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4928]
Expected prepareForTestingBeta to work smoothly. However it gives error for me:

```
$ npm run backend-ops prepareForTestingBeta

> blockframes@0.0.2 backend-ops D:\C8\blockframes-dev
> ts-node -P tools/tsconfig.tools.json apps/backend-ops/src/main.ts "prepareForTestingBeta"

{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
Please ensure the following variable is set in .env : IMGIX_TOKEN
More info: API key for imgIx CDN is missing. Please see: https://www.notion.so/cascade8/Setup-ImgIx-c73142c04f8349b4a6e17e74a9f2209a

Please ensure the following variable is set in .env : PROJECT_ID
More info: Please specify your Firebase projectId in your .env file. This is used when executing build and deploy commands, such as nx deploy or nx build

Ensuring maintenance mode stays active in Firestore
Copying AnonDb from CI...
Clearing old golden data: gsutil -m -q rm -r "gs://mano-backups/LATEST-ANON-DB/*"
Copying golden data from CI gsutil -m -q cp -r gs://ci-backups-blockframes/LATEST-ANON-DB gs://mano-backups
Copied!
Clearing Firestore db and importing latest anonymized db...
Deleted _VERSION in _META
Run: gcloud firestore import --project blockframes-mano gs://mano-backups/LATEST-ANON-DB
ERROR: (gcloud.firestore.import) PERMISSION_DENIED: The caller does not have permission
Error: Command failed: gcloud firestore import --project blockframes-mano gs://mano-backups/LATEST-ANON-DB
ERROR: (gcloud.firestore.import) PERMISSION_DENIED: The caller does not have permission

    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Object.<anonymous> (D:\C8\blockframes-dev\libs\firebase-utils\src\lib\firestore\import.ts:115:15)
    at step (D:\C8\blockframes-dev\libs\firebase-utils\src\lib\firestore\import.ts:33:23)
    at Object.next (D:\C8\blockframes-dev\libs\firebase-utils\src\lib\firestore\import.ts:14:53)
    at fulfilled (D:\C8\blockframes-dev\libs\firebase-utils\src\lib\firestore\import.ts:5:58) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 45 52 52 4f 52 3a 20 28 67 63 6c 6f 75 64 2e 66 69 72 65 73 74 6f 72 65 2e 69 6d 70 6f 72 74 29 20 50 45 52 4d 49 53 53 49 4f 4e 5f 44 45 4e 49 45 44 ... 39 more bytes>
  ],
  pid: 4452,
  stdout: <Buffer >,
  stderr: <Buffer 45 52 52 4f 52 3a 20 28 67 63 6c 6f 75 64 2e 66 69 72 65 73 74 6f 72 65 2e 69 6d 70 6f 72 74 29 20 50 45 52 4d 49 53 53 49 4f 4e 5f 44 45 4e 49 45 44 ... 39 more bytes>
}
Time running command "prepareForTestingBeta": 11.340s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockframes@0.0.2 backend-ops: `ts-node -P tools/tsconfig.tools.json apps/backend-ops/src/main.ts "prepareForTestingBeta"`
npm ERR! Exit status 1
npm ERR!
```

The issue should have been caught by healthCheck?

```
> ts-node -P tools/tsconfig.tools.json apps/backend-ops/src/main.ts "healthCheck"

{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
Please ensure the following variable is set in .env : IMGIX_TOKEN
More info: API key for imgIx CDN is missing. Please see: https://www.notion.so/cascade8/Setup-ImgIx-c73142c04f8349b4a6e17e74a9f2209a

Please ensure the following variable is set in .env : PROJECT_ID
More info: Please specify your Firebase projectId in your .env file. This is used when executing build and deploy commands, such as nx deploy or nx build

Local Backup Bucket - CREATE FILE: ALLOW
Local Backup Bucket - GET FILE: ALLOW
Local Backup Bucket - DELETE FILE: ALLOW
Local Backup Bucket - LIST FILE: ALLOW
Local tmp Folder - WRITE: ALLOW
Local tmp Folder - READ: ALLOW
CI Backup Bucket - GET FILE: ALLOW
CI Backup Bucket - LIST FILE: ALLOW
CI Storage Backup Bucket - GET FILE: ALLOW
CI Storage Backup Bucket - LIST FILE: ALLOW
Firestore Access: ALLOW
Time running command "healthCheck": 1:43.551 (m:ss.mmm)
```

**Comment by phpgeekfr** [comment]
Did you faced the issue again @xmano ? If you don't have it anymore and if we don't have a way to reproduce it, I think we can close

**Comment by xmano** [comment]
It worked for me subsequently. If we see this again we can re-open or file a new one.
