### ISSUE TITLE
Emulator : Improvements for deploying function

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#7263]
While debugging the scenario where user auth record exists but user could not be authenticated, it was felt that the way functions are currently deployed to emulator can be improved.

Some logs for ref:

```
Writing Firebase Functions config secrets to .runtimeConfig
Firestore backup detected correctly.  <===


i  emulators: Starting emulators: auth, functions, firestore, pubsub
!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: database, hosting, storage
+  functions: Using node@12 from host.
!  functions: Your GOOGLE_APPLICATION_CREDENTIALS environment variable points to D:/C8/bf-exper/tools/credentials/blockframes-mano-firebase-adminsdk-378rr-2fa9b3a76a.json. 

i  firestore: Importing data from D:\C8\bf-mano\.firebase\emulator\firestore_export\firestore_export.overall_export_metadata

```

**Comment by xmano** [comment]
Enhancement request

After shutting down emulator, starting it next time using `npm start emulators` causes issues:

![image](https://user-images.githubusercontent.com/8731418/143858574-c6133729-6ef3-48b4-bdea-b1b0074ae89d.png)

If we could use the last backup it will be good.

**Comment by xmano** [comment]
Restarting emulator is not working reliably. It fails to read config values:

```
>  e2e Mode enabled for functions
>  These are the emulated functions.config values present in .runtimeConfig
>  {}
!  It looks like you're trying to access functions.config().sendgrid but there is no value there. You can learn more about setting up config here: https://firebase.google.com/docs/functions/local-emulator
!  TypeError: Cannot read property 'api_key' of undefined
    at Object.<anonymous> (D:\C8\bf-exper\dist\apps\backend-functions\main.js:639:53)
    at __webpack_require__ (D:\C8\bf-exper\dist\apps\backend-functions\main.js:20:30)
    at Object.<anonymous> (D:\C8\bf-exper\dist\apps\backend-functions\main.js:315:23)
    at __webpack_require__ (D:\C8\bf-exper\dist\apps\backend-functions\main.js:20:30)
    at Object.<anonymous> (D:\C8\bf-exper\dist\apps\backend-functions\main.js:5149:20)
    at __webpack_require__ (D:\C8\bf-exper\dist\apps\backend-functions\main.js:20:30)
    at Object.<anonymous> (D:\C8\bf-exper\dist\apps\backend-functions\main.js:5119:18)
    at __webpack_require__ (D:\C8\bf-exper\dist\apps\backend-functions\main.js:20:30)
    at D:\C8\bf-exper\dist\apps\backend-functions\main.js:84:18
    at Object.<anonymous> (D:\C8\bf-exper\dist\apps\backend-functions\main.js:87:10)
!  We were unable to load your functions code. (see above)

```

Althoug the API key exists in .runtimeconfig.json
