### ISSUE TITLE
anon-db-process is failing

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8261]
Anondb process have a new bug
https://app.circleci.com/pipelines/github/blockframes/blockframes/24889/workflows/f8127bf7-48fd-431e-a666-654afc9275d2/jobs/57183

```
Loading Firestore. Please wait ...
Unable to shut down emulator process, forcing export and killing emulator...
i  Found running emulator hub for project blockframes-ci at http://localhost:4400
i  Exporting data to: /home/circleci/repo/.firebase/emulator
i  emulators: Received export request. Exporting data to /home/circleci/repo/.firebase/emulator.
✔  emulators: Export complete.
✔  Export complete
ERROR!
 GoogleError: Total timeout of API google.firestore.v1.Firestore exceeded 60000 milliseconds before any response was received.
    at repeat (/home/circleci/repo/node_modules/@google-cloud/firestore/node_modules/google-gax/src/normalCalls/retries.ts:84:23)
    at Timeout._onTimeout (/home/circleci/repo/node_modules/@google-cloud/firestore/node_modules/google-gax/src/normalCalls/retries.ts:125:13)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 4
}
```

it fails at loading invitation collection because it takes more than 60 sec
looks like a bug introducted in the libraries update

**Comment by phpgeekfr** [comment]
`invitation` collection was containing too many docs and `promise.all(promises) ` with around 4k docs created to many calls to firestore at the same time, resulting in a timeout.

https://app.circleci.com/pipelines/github/blockframes/blockframes/25037/workflows/634f376f-8630-4d09-b41e-14c28491e4d9/jobs/58109

https://github.com/blockframes/blockframes/pull/8278
